services:
  postgres_db:
    image: postgres:16-alpine
    restart: always
    shm_size: 512mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  web:
      build: .
      restart: always
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - 8000:8000
      env_file:
        - .env
      depends_on:
        - postgres_db
        - rabbitmq

  celery_worker:
    build: .
    restart: always
    command: celery -A todolist.async_tasks worker --loglevel=info --concurrency 8
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
      - rabbitmq

  celery_beat:
    build: .
    restart: always
    command: celery -A todolist.async_tasks beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
      - rabbitmq

volumes:
    postgres_data:
    rabbitmq_data: