# Generated by Django 6.0.6 on 2026-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
