# Generated by Django 6.0.6 on 2026-07-08 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_reminderlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderlog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
